apiVersion: v1
kind: Service
metadata:
  name: ntb-app-service
  labels:
    app: ntb-app
spec:
  type: NodePort
  selector:
    app: ntb-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: http
